#!/bin/bash

set -e

if [ -z "$1" ]; then
  echo "Usage: $0 PULL_NUMBER"
  exit 1
fi

pull_number=$1

set -u

gh api "repos/{owner}/{repo}/pulls/${pull_number}/update-branch" \
  --silent \
  --method PUT
